# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class JavabinCli < Formula
  desc "Developer CLI for the Javabin platform"
  homepage "https://github.com/javaBin/javabin-cli"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/javaBin/javabin-cli/releases/download/v0.1.0/javabin-cli_0.1.0_darwin_amd64.tar.gz"
      sha256 "5fc561bcd57dc3ff5050d9457e3f430050b34050661641bb587a7df059a676a0"

      define_method(:install) do
        bin.install "javabin"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/javaBin/javabin-cli/releases/download/v0.1.0/javabin-cli_0.1.0_darwin_arm64.tar.gz"
      sha256 "c48fb2c9646de2992c764658da3bc6288db1cd49227ef7f57d55f71e2893d7cb"

      define_method(:install) do
        bin.install "javabin"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/javaBin/javabin-cli/releases/download/v0.1.0/javabin-cli_0.1.0_linux_amd64.tar.gz"
      sha256 "ea1eb9497abcb30a5af9be57512e286a13ab954b5e1a37bed36dfb4bc95fcf0f"
      define_method(:install) do
        bin.install "javabin"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/javaBin/javabin-cli/releases/download/v0.1.0/javabin-cli_0.1.0_linux_arm64.tar.gz"
      sha256 "945b35b29afafb200ba81d802be523e7709c45cf3e20ee070d5edb968be7a164"
      define_method(:install) do
        bin.install "javabin"
      end
    end
  end
end
